### ISSUE TITLE
Maybe make organisation?

### ISSUE THREAD

**Issue by herrjemand** [IonicaBizau/made-in-brazil#2]
I think at some point you'll need org for that

**Comment by herrjemand** [comment]
github/madein ?

**Comment by IonicaBizau** [comment]
That's a good idea. I was thinking at that, but I'm not sure what should be the name. 😁 `made-in` is already taken and I don't really like `madein`...

**Comment by herrjemand** [comment]
Account looks dead.

**Comment by herrjemand** [comment]
@IonicaBizau /`developedat`?

**Comment by alehander42** [comment]
you can always put an `awesome-` in the beginning :laughing:

**Comment by IonicaBizau** [comment]
I registered @oss-made-in. We can rename it once we have a better name. If you want to be part of it, feel free to 🔔 me. 🚀

**Comment by herrjemand** [comment]
@IonicaBizau Awesome! :+1:

**Comment by herrjemand** [comment]
@IonicaBizau P.S. How did you generate the lists?

**Comment by herrjemand** [comment]
@IonicaBizau ossmade.in is free as well*)

**Comment by herrjemand** [comment]
@IonicaBizau maybe fossmade.in?

**Comment by alehander42** [comment]
Another thing you can do is to generate a list grouped by categories (web, servers, auth etc)
You can use the existing awesome-x lists and match projects from there (you could use standard files like `package.json or setup.py` and README for keywords but that might be out of scope for the org)
