### ISSUE TITLE
Improvement: add react-vanilla-form

### ISSUE THREAD

**Issue by Deivis** [IonicaBizau/made-in-brazil#29]
This issue aims to add [react-vanilla-form](https://github.com/derekstavis/react-vanilla-form) to the list, the library provides an awesome experience for making simple forms using react and it could be very useful to `react` users which are trying to avoid big and complex form libraries.

Platform: web
Language: JavaScript
Repository:  https://github.com/derekstavis/react-vanilla-form

**Comment by IonicaBizau** [comment]
Feel free to create a pull request. 😄
