### ISSUE TITLE
Suico

### ISSUE THREAD

**Issue by mambax7** [IonicaBizau/made-in-brazil#32]
I would like to add a XOOPS module called Suico, that was created by [Marcello Brandão from Brazil, aka  Suico](https://xoops.org/modules/news/article.php?storyid=5217), who unfortunately passed away due to cancer 10 years ago. 

His most popular module was the [Yogurt Social Media module for XOOPS](https://github.com/XoopsModules25x/suico), but as we were updating it for PHP 7, we thought that to honor his memory, we'll rename it to SUICO, the nickname he used. 

Let me know if this would be possible...

**Comment by IonicaBizau** [comment]
Sure, just create a pull request. Thanks!
